name: publish-beta

on:
  push:
    branches: [ main ]
    paths:
        - 'DH.NMQ/**'
  pull_request:
    branches: [ main ]
    paths:
        - 'DH.NMQ/**'
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Get Version
      run: echo "VERSION=$(date '+%Y.%m%d-beta%H%M')" >> $GITHUB_ENV
    - name: Build
      run: |
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NMQ/DH.NMQ.csproj

    - name: Publish
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/PeiKeSmart/index.json --api-key ${{ github.token }}
